[book]
authors = ["Jonathan Dönszelmann <jonabent@gmail.com>", "Jake \"ferris\" Taylor <yupferris@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Kaze"

[build]
build-dir = "output"
